DoctorApplication/DoctorApplication/Controllers/DoctorController.cs
using ClosedXML.Excel;
using DoctorApplication.Classes;
using DoctorApplication.Models;
using DoctorApplication.Models.DbEntities;
using DoctorApplication.Models.Doctor;
using DoctorApplication.Models.Home;
using DoctorApplication.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.ObjectModel;
using System.Data;

namespace DoctorApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class DoctorController : Controller
    {
        private DoctorAppDbContext context;
        private readonly IEmailTemplateService templateService;
        public DoctorController(DoctorAppDbContext Context, IEmailTemplateService templateService)
        {
            this.context = Context;
            templateService = templateService;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 5;
            var count = await context.doctors.CountAsync();
            var items = await context.doctors.Include(d => d.specialities).Include(d=>d.account).Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            var types = context.doctorSpecialities.ToList();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            DoctorViewModel viewModel = new DoctorViewModel
            {
                pageViewModel = pageViewModel,
                doctors = items,
                doctorTypes = types
            };
            return View(viewModel);
        }


        [HttpPost]
        [HttpGet]
        public async Task<IActionResult> Appointments(int idDoc, int page = 1)
        {
            if (idDoc is 0)
            {
                return RedirectToAction("Index");
            }
            int pageSize = 5;
            var count = 0;
            var items = new List<Appointment>();
            try
            {
                count = await context.appointments.Include(a => a.doctor).Where(a => a.doctor.id == idDoc).CountAsync();
                items = await context.appointments.Include(a => a.doctor).Where(a => a.doctor.id == idDoc).Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            }catch(Exception e)
            {
                count = 0;
                items = new List<Appointment>();
            }
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            AppointmentsViewModel viewModel = new AppointmentsViewModel
            {
                idDoctor = idDoc,
                pageViewModel = pageViewModel,
                appointments = items
            };
            Doctor doc = context.doctors.Where(d => d.id == idDoc).FirstOrDefault();
            try
            {
                doc.appointmentNum = context.appointments.Include(a => a.doctor).Where(a => a.doctor.id == doc.id).Count();
            }
            catch(Exception e)
            {
                doc.appointmentNum = 0;
            }
            context.SaveChanges();
            return View(viewModel);
        }

        public IActionResult EditDoctor(int idDoc, int page)
        {
            if (idDoc is 0)
                return RedirectToAction("AddDoctor");

            var doctor = context.doctors.Include(d => d.specialities).FirstOrDefault(d => d.id == idDoc);
            if (doctor is null)
                return RedirectToAction("AddDoctor");
            var types = context.doctorSpecialities.Where(d => d.enabled == true);
            return View("DoctorAddMod", new DoctorSpecialityModel { doctor = doctor, doctorSpecialities = types });
        }


        public IActionResult AddMod(DoctorSpecialityModel model, int[] ids, IFormFile file, int page = 1)
        {
            if (model.doctor.id is 0)
            {
                if (model.doctor.surrname is null || model.doctor.name is null || model.doctor.account.email is null || model.doctor.tel is null) return RedirectToAction("AddDoctor");
            }
            var doctor = context.doctors.Include(d => d.specialities).Include(d=>d.account).FirstOrDefault(d => d.id == model.doctor.id);
            var types = context.doctorSpecialities.Where(d => ids.Contains(d.id)).ToList();
            if (doctor is null)
                return RedirectToAction("AddDoctor");
            doctor.surrname = model.doctor.surrname;
            doctor.name = model.doctor.name;
            doctor.account.email = model.doctor.account.email;
            doctor.tel = model.doctor.tel;

            var typesDelDif = doctor.specialities.Except(types).ToList();
            var typesAddDif = types.Except(doctor.specialities).ToList();
            foreach (var type in typesDelDif)
            {
                doctor.specialities.Remove(type);
            }

            foreach (var type in typesAddDif)
            {
                doctor.specialities.Add(type);
            }

            if (file != null) doctor.imageString = ImageStringConvert.ConvertImageToString(file);
            context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Modified Doctor/Id = " + doctor.id,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Succes"
                ));
            context.SaveChanges();
            return RedirectToAction("Index", new { page = page });
        }

        public IActionResult Enable(int idDoc, int page)
        {
            if (idDoc is 0)
            {
                context.logEvents.Add(LogEvent.createLog(
                    HttpContext.Connection.RemoteIpAddress?.ToString(),
                    "Enabled Doctor/id = " + idDoc,
                    context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                    "Error"
                    ));
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            if (context.doctors.Any(d => d.id == idDoc) == false)
            {
                context.logEvents.Add(LogEvent.createLog(
                    HttpContext.Connection.RemoteIpAddress?.ToString(),
                    "Enabled Doctor/id = " + idDoc,
                    context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                    "Error"
                    ));
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            var doc = context.doctors.FirstOrDefault(d => d.id == idDoc);
            doc.activityStatus = true;
            context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Enabled Doctor/id = " + idDoc,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Succes"
                ));
            context.SaveChanges();
            return RedirectToAction("Index", new { page = page });
        }

        public IActionResult Disable(int idDoc, int page)
        {
            if (idDoc is 0)
            {
                context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Disabled Doctor/id = " + idDoc,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Error"
                ));
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            if (context.doctors.Any(d => d.id == idDoc) == false)
            {
                context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Disabled Doctor/id = " + idDoc,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Error"
                ));
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            var doc = context.doctors.FirstOrDefault(d => d.id == idDoc);
            doc.activityStatus = false;
            context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Disabled Doctor/id = " + idDoc,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Succes"
                ));
            context.SaveChanges();
            return RedirectToAction("Index", new { page = page });
        }

        public IActionResult Back(int page)
        {
            if (page < 1) page = 1;
            return RedirectToAction("Index", new { page = page });
        }

        public ActionResult SetDateEndLimit(DateTime date)
        {
            return Json(date.ToString("yyyy-MM-dd"));
        }

        public ActionResult SetTimeEndLimit(string time, bool dateCheck)
        {
            List<string> baseTimes = new List<string> {
                "08:00",
                "08:30",
                "09:00",
                "09:30",
                "10:00",
                "10:30",
                "11:00",
                "11:30",
                "12:00",
                "13:00",
                "13:30",
                "14:00",
                "14:30",
                "15:00",
                "15:30",
                "16:00",
                "16:30",
                "17:00"
            };
            if (dateCheck is false)
            {
                return Json(baseTimes);
            }
            List<string> times = new List<string>();
            foreach (string s in baseTimes)
            {
                if (s.CompareTo(time) >= 0) times.Add(s);

            }
            return Json(times);
        }


        [HttpPost]
        public IActionResult Export(DateTime dateStart, DateTime dateEnd, string timeStart, string timeEnd, int idDoc)
        {

DoctorApplication/DoctorApplication/Controllers/LogsController.cs
using DoctorApplication.Models;
using DoctorApplication.Models.Home;
using DoctorApplication.Models.Logs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoctorApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class LogsController : Controller
    {
        DoctorAppDbContext context;
        public LogsController(DoctorAppDbContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 5;
            var count = await context.logEvents.CountAsync();
            var items = await context.logEvents.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            LogsModel viewModel = new LogsModel
            {
                pageViewModel = pageViewModel,
                logs = items
            };
            return View(viewModel);
        }
    }
}

DoctorApplication/DoctorApplication/Controllers/StatisticsController.cs
using DoctorApplication.Models;
using DoctorApplication.Models.Statistics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DoctorApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class StatisticsController : Controller
    {
        private DoctorAppDbContext context;
        public StatisticsController(DoctorAppDbContext Context)
        {
            this.context = Context;
        }
        public IActionResult Index()
        {
            List<int> eachRoleNum = new List<int>();
            eachRoleNum.Add(context.accounts.Where(u => u.role == 0).Count());
            eachRoleNum.Add(context.accounts.Where(u => u.role == 1).Count());

            List<int> activitycount = new List<int>();
            activitycount.Add(context.doctors.Where(d => d.activityStatus == true).Count());
            activitycount.Add(context.doctors.Where(d => d.activityStatus == false).Count());

            var doctorsNames = context.doctors.Where(d => d.activityStatus == true).Select(d => d.surrname + " " + d.name);
            var doctorsAppointmentNum = context.doctors.Where(d => d.activityStatus == true).Select(d => d.appointmentNum);
            StatisticsModel sw = new StatisticsModel { eachRoleNum = eachRoleNum, activityCount = activitycount, doctorsNames = (IEnumerable<string>)doctorsNames, doctorsAppointmentNum = (IEnumerable<int>)doctorsAppointmentNum };
            return View(sw);
        }
    }
}

DoctorApplication/DoctorApplication/Controllers/UsersController.cs
using DoctorApplication.Models;
using DoctorApplication.Models.DbEntities;
using DoctorApplication.Models.Home;
using DoctorApplication.Models.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoctorApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        DoctorAppDbContext context;
        public UsersController(DoctorAppDbContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 5;
            var count = await context.accounts.CountAsync();
            var items = await context.accounts.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            UsersModel viewModel = new UsersModel
            {
                pageViewModel = pageViewModel,
                users = items
            };
            return View(viewModel);
        }

        public IActionResult EditVerification(int idUser, int page)
        {
            if (idUser is 0)
                return RedirectToAction("Index");
            if (context.accounts.Any(d => d.id == idUser) == false)
                return RedirectToAction("Index");
            var user = context.accounts.FirstOrDefault(d => d.id == idUser);
            if (user.verified) user.verified = false;
            else user.verified = true;

            context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Edited User Verification/id = " + user.id,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Succes"
            ));
            context.SaveChanges();
            return RedirectToAction("Index", new { page = page });
        }

        public IActionResult GrantAdmin(int idUser, int page)
        {
            if (idUser is 0)
                return RedirectToAction("Index");
            if (context.accounts.Any(d => d.id == idUser) == false)
                return RedirectToAction("Index");
            var user = context.accounts.FirstOrDefault(d => d.id == idUser);
            user.role = 1;
            context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Edited User/Granted Admin/id = " + user.email,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Succes"
            ));
            context.SaveChanges();
            return RedirectToAction("Index", new { page = page });
        }

        public IActionResult TakeAdmin(int idUser, int page)
        {
            if (idUser is 0)
                return RedirectToAction("Index");
            if (context.accounts.Any(d => d.id == idUser) == false)
                return RedirectToAction("Index");
            var user = context.accounts.FirstOrDefault(d => d.id == idUser);
            user.role = 0;
            context.logEvents.Add(LogEvent.createLog(
                HttpContext.Connection.RemoteIpAddress?.ToString(),
                "Edited User/Removed Admin/id = " + user.email,
                context.accounts.Where(u => u.email == User.Identity.Name).FirstOrDefault(),
                "Succes"
            ));
            context.SaveChanges();
            return RedirectToAction("Index", new { page = page });
        }

        public IActionResult Back(int page)
        {
            if (page < 1) page = 1;
            return RedirectToAction("Index", new { page = page });
        }
    }
}

DoctorApplication/DoctorApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DoctorApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/pagination.css" />
    <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">DoctorApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1" style="margin-top:25px;">
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <div class="input-group mb-3">
                                        <form asp-controller="Account" asp-action="SetLanguage"
                                              asp-route-returnUrl="@Context.Request.Path"
                                              method="post" class="form-horizontal">
                                            <select class="custom-select" name="culture" onchange="this.form.submit();">
                                                <option selected value="">@Localizer["Language"]</option>
                                                <option value="ro">Română</option>
                                                <option value="en">English</option>
                                            </select>
                                        </form>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                                </li>
                                @if (User.IsInRole("admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">@Localizer["Doctors"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="DoctorSpecialities" asp-action="Index">@Localizer["DoctorTypes"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="DoctorApplicationConfirmation">@Localizer["DoctorApplicationConfirmation"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">@Localizer["Users"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Localization" asp-action="Index">@Localizer["Localization"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Index">@Localizer["Statistics"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Logs" asp-action="Index">@Localizer["Logs"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">@Localizer["Log out"]</a>
                                    </li>
                                }
                            }

                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">@Localizer["Login"]</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-3.6.0.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.timepicker.min.js" asp-append-version="true"></script>
    <script src="~/js/getDate.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>